-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 15:02:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_stock` DEFAULT CHARACTER SET utf8 ;
USE `data_stock` ;

-- -----------------------------------------------------
-- Table `data_stock`.`Convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_stock`.`Convention` (
  `idConvention` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `nbHeur` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idConvention`),
  UNIQUE INDEX `idConvention_UNIQUE` (`idConvention` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_stock`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_stock`.`Etudiant` (
  `idEtudiant` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(200) NOT NULL,
  `Convention` INT NOT NULL,
  PRIMARY KEY (`idEtudiant`),
  UNIQUE INDEX `idEtudiant_UNIQUE` (`idEtudiant` ASC) VISIBLE,
  INDEX `fk_Etudiant_Convention1_idx` (`Convention` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiant_Convention1`
    FOREIGN KEY (`Convention`)
    REFERENCES `data_stock`.`Convention` (`idConvention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_stock`.`Attestation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_stock`.`Attestation` (
  `idAttestation` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `Etudiant` INT NOT NULL,
  `Convention` INT NOT NULL,
  PRIMARY KEY (`idAttestation`, `Etudiant`, `Convention`),
  UNIQUE INDEX `idAttestation_UNIQUE` (`idAttestation` ASC) VISIBLE,
  INDEX `fk_Attestation_Etudiant_idx` (`Etudiant` ASC) VISIBLE,
  INDEX `fk_Attestation_Convention1_idx` (`Convention` ASC) VISIBLE,
  CONSTRAINT `fk_Attestation_Etudiant`
    FOREIGN KEY (`Etudiant`)
    REFERENCES `data_stock`.`Etudiant` (`idEtudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attestation_Convention1`
    FOREIGN KEY (`Convention`)
    REFERENCES `data_stock`.`Convention` (`idConvention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
